CREATE DATABASE mydatabase;
USE mydatabase;
USE mydatabase;
SHOW TABLES;
ALTER USER 'pythonuser'@'localhost' IDENTIFIED BY 'Sgk1@ggk';
GRANT ALL PRIVILEGES ON mydatabase.* TO 'pythonuser'@'localhost';
FLUSH PRIVILEGES;
DROP USER 'pythonuser'@'localhost';
CREATE USER 'pythonuser'@'localhost' IDENTIFIED BY 'Sgk1@ggk';
GRANT ALL PRIVILEGES ON mydatabase.* TO 'pythonuser'@'localhost';
FLUSH PRIVILEGES;
USE mydatabase;
SHOW TABLES;
SELECT COUNT(*) FROM customer_purchase;
SELECT * FROM customer_purchase
LIMIT 10;

-- what is total revenue generated by males vs female customers?
Select 
    gender,
    sum(purchase_amount) as total_revenue
FROM customer_purchase
group by gender;

-- Which customers used a discount but still spent more than the average purchase amount ?


SELECT 
    customer_id, purchase_amount
FROM customer_purchase 
where discount_applied = 'Yes' and
	  purchase_amount >(
          select avg(purchase_amount) 
          from customer_purchase);
          
-- which are the top 5 products with the highest average revenue rating?
SELECT
    item_purchased, 
    ROUND(avg(review_rating),2) as avg_review_rating
FROM customer_purchase
group by item_purchased
order by avg_review_rating DESC
LIMIT 5;

-- Compare the average Purchase Amounts between Standard and express Shipping
SELECT 
    shipping_type,
    round(AVG(purchase_amount),2) as avg_purchase_amount
FROM customer_purchase
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non subscribers
SELECT 
    subscription_status, 
    AVG(purchase_amount) as avg_purchase_amount,
    COUNT(customer_id) as total_customers,
    SUM(purchase_amount) as total_revenue
FROM customer_purchase
group by subscription_status
order by avg_purchase_amount, total_revenue DESC; 

-- Which 5 products have the highest percentage of purchases with discounts applied ?
SELECT 
    item_purchased,
    ROUND(100* SUM(CASE WHEN discount_applied = 'Yes' then 1 else 0 end )/count(*),2)  as purchase_percentage 
FROM customer_purchase
group by item_purchased
order by purchase_percentage DESC
LIMIT 5 ;

-- Segment customers into new, returning , and loyal based  on their total  number of previous purchases, and show the count of each segment.
WITH customer_type as (
    Select 
        customer_id, previous_purchases,
        CASE WHEN previous_purchases = 1 then 'new'
		when previous_purchases between 2 and 10 then 'returning'
        else 'loyal'
        end  as Customer_segment
	FROM customer_purchase)
    select customer_segment, count(*) as number_customers
    from customer_type 
    group by customer_segment;
    
-- What are the top 3 most purchased products within each category 
SELECT *
FROM (
    SELECT 
        item_purchased,
        category,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank_num
    FROM customer_purchase
    GROUP BY category, item_purchased
) t
WHERE rank_num <= 3;



-- Are customers who are repeat buyers(more than 5 previous purchases) and also likely to subscribe 

SELECT 
    count(customer_id) as customer_count,
	subscription_status
FROM customer_purchase
where previous_purchases > 5 
group by subscription_status;

-- What is the revenue contribution of each age group 
SELECT 
sum(purchase_amount) as total_revenue,
age_group 
FROM customer_purchase
group by age_group
order by total_revenue DESC


    
    
    
        
    
  



